### ISSUE TITLE
`catkin_make` error after ROS install

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-ros-base#2]
Steps to reproduce:
1. `yay -Syu ros-melodic-desktop-full`
2. Create a catkin workspace as described [here](https://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment).
3. `catkin_make` the workspace
Expected output: Successful build
Actual output:
```
Base path: /home/acxz/Desktop/ros-melodic/tutorial_ws
Source space: /home/acxz/Desktop/ros-melodic/tutorial_ws/src
Build space: /home/acxz/Desktop/ros-melodic/tutorial_ws/build
Devel space: /home/acxz/Desktop/ros-melodic/tutorial_ws/devel
Install space: /home/acxz/Desktop/ros-melodic/tutorial_ws/install
####
#### Running command: "cmake /home/acxz/Desktop/ros-melodic/tutorial_ws/src -DCATKIN_DEVEL_PREFIX=/home/acxz/Desktop/ros-melodic/tutorial_ws/devel -DCMAKE_INSTALL_PREFIX=/home/acxz/Desktop/ros-melodic/tutorial_ws/install -G Unix Makefiles" in "/home/acxz/Desktop/ros-melodic/tutorial_ws/build"
####
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using CATKIN_DEVEL_PREFIX: /home/acxz/Desktop/ros-melodic/tutorial_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using default Python package layout
-- Could NOT find PY_em (missing: PY_EM) 
CMake Error at /opt/ros/melodic/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/all.cmake:163 (include)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:56 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/acxz/Desktop/ros-melodic/tutorial_ws/build/CMakeFiles/CMakeOutput.log".
Invoking "cmake" failed
```
`python-empy` is installed

**Comment by acxz** [comment]
The mention of this issue is on the AUR page of `python-empy` but I am not clear as to what the solution was? From what I understand this issue was fixed, but is still occurring for me.

**Comment by jwhendy** [comment]
Observation:
```
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
```

Try:
```
$ pip2 freeze | grep em
$ pip3 freeze | grep em
```

**Comment by jwhendy** [comment]
Maybe relevant... I noticed my `~/catkin_ws` was looking for `python2` as well, but built, wasn't getting any errors, killed the build, then mucked with `ROS_PYTHON_VERSION` and tried to build again, and failed to find a suitable `python` interpreter. Then I couldn't fix it!

In searching, I found [this post](https://medium.com/@beta_b0t/how-to-setup-ros-with-python-3-44a69ca36674) and ran the following, which has me building again:
```
cd ~/catkin_ws
catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m -DPYTHON_LIBRARY=/usr/lib/libpython3.7m.so
```

Maybe helpful for you (ensuring ROS is picking up the right python version and module location)?

**Comment by acxz** [comment]
Regarding your first comment, I do not have pip2 or pip3 installed.

I ran catkin_make with your provided command and it was able to build it successfully. Is there anyway I can catkin_make without typing those flags every time, other than an alias?

**Comment by jwhendy** [comment]
I ran that `catkin config` command once, then just pure `catkin build` and everything was fine. I just did `catkin clean` and then `catkin build` and the `python3.7` settings persisted.

I think after you do it once, you should be good. I'm not sure where this setting is stored, though... like will it persist with an upgrade of `ros-melodic-catkin`? Not sure. I put it in my `.bashrc` under the commands to source `bash.setup` files just so I have it around in case I have to re-run.

**Comment by acxz** [comment]
So actually I am not able to use `catkin config` or `catkin build`. I had to run the following command:
`catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m -DPYTHON_LIBRARY=/usr/lib/libpython3.7m.so`
Running `catkin config ...` results in: `command not found: catkin`. `/opt/ros/melodic/setup.zsh` is sourced.

**Comment by jwhendy** [comment]
I use `python-catkin_tools` (`catkin`), not `ros-melodic-catkin` (`catkin_make`). Here's [some info](https://catkin-tools.readthedocs.io/en/latest/migration.html) on the difference. I don't recall exactly when/why I switched, but at the very least it looks better :) 

One of the potentially relevant benefits to `catkin` is:

>It stores persistent configuration options in a .catkin_tools directory at the root of your workspace.

This might be why that `catkin config` command then lives on in the workspace for future builds.

**Comment by acxz** [comment]
I see thank you for letting me know, I got `catkin config` and `catkin build` to work!
