### ISSUE TITLE
Coaching on using oscloud binaries (pgp key woes)?

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-ros-base#3]
Feeling dumb here. What am I doing wrong?

- added oscloud to `pacman.conf`
- `pacman -Syu`

```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra                   1663.9 KiB  3.05 MiB/s 00:01 [############################] 100%
 community is up to date
 custom is up to date
 oscloud                  299.3 KiB   537 KiB/s 00:01 [############################] 100%
 oscloud.sig              566.0   B  4.16 KiB/s 00:00 [############################] 100%
error: oscloud: key "289AD6AA32857A04ABA587417EAC11ACDBCFBCEB" is unknown
:: Import PGP key 289AD6AA32857A04ABA587417EAC11ACDBCFBCEB? [Y/n] Y
error: key "289AD6AA32857A04ABA587417EAC11ACDBCFBCEB" could not be looked up remotely
error: failed to update oscloud (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

- google "how to import key" and tried `gpg`
```
$ gpg --receive-keys 289AD6AA32857A04ABA587417EAC11ACDBCFBCEB
gpg: keyserver receive failed: General error
```

- hmmm, consulted [wiki](https://wiki.archlinux.org/index.php/Pacman/Package_signing#Adding_developer_keys) and tried to use `pacman-key`
```
$ sudo pacman-key --recv-keys 289AD6AA32857A04ABA587417EAC11ACDBCFBCEB
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.
```
- grrrr! Looking around some more, found a [list of user repos](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#oscloud), which lists a different key?
```
$ sudo pacman-key --recv-keys CB222E7EBC11D682AAC8B317A4A0D73114FDE6FC
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.

$ gpg --receive-keys CB222E7EBC11D682AAC8B317A4A0D73114FDE6FC
gpg: keyserver receive failed: General error
```

What am I doing wrong here?

**Comment by bionade24** [comment]
Sorry yes, `CB222E7EBC11D682AAC8B317A4A0D73114FDE6FC` is the right one. If you can't retrieve it, try to set `--keyserver keyserver.ubuntu.com` as flag. Then it should work. Could you please tell me where you found the old key?

**Comment by jwhendy** [comment]
I'll try that later today (in windows at the moment). The old key was auto-prompted when I added `oscloud` to `pacman.conf` and did `pacman -Syu` as shown above. It recognized I didn't have a key with that repo and asked me if I wanted to add, but failed when I says `Y`.

I'm not clear on how key servers work, but could a stale one be stored on Arch servers somewhere (wherever pacman checks)?

**Comment by bionade24** [comment]
> I'll try that later today (in windows at the moment). The old key was auto-prompted when I added `oscloud` to `pacman.conf` and did `pacman -Syu` as shown above. It recognized I didn't have a key with that repo and asked me if I wanted to add, but failed when I says `Y`.
The maybe it's just a subkey. Maybe it  will work, too or perhaps pacman shows the wrong.
> I'm not clear on how key servers work, but could a stale one be stored on Arch servers somewhere (wherever pacman checks)?
Key servers have nothing to do with Arch. pacman downloads the TU keyring and add it to your local keyring without relying to on keyserver infrastructure.

**Comment by jwhendy** [comment]
I'll trust you on that but what I mean is that _somehow_ `pacman` (or what it uses) thinks your key is `289AD6AA32857A04ABA587417EAC11ACDBCFBCEB`.

```
[oscloud]
Server = http://repo.oscloud.info/
```
and run `pacman -Syu` and it tries to add that key, which [indeed](https://archived.forum.manjaro.org/t/receving-error-while-installing-ros-melodic-desktop-full/114913) is an old key.
I looked after and that fingerprint is from my current key. I first thought somewhere on the web there is a guide with my old key and confused you.

Maybe the import is just fine, but the trust level isn't. If you don't trust the key pacman won't do anything.

**Comment by bionade24** [comment]
Fail. I don't know why but it's the first time I accidentally edited the comment instead of replying. Sorry.

**Comment by bionade24** [comment]
Btw: The packages are probably currently a bit out of date. The new CI/CD with [Webinterface](https://abs-cd.oscloud.info) is already running, hopefully I fixed all issues now.

**Comment by bionade24** [comment]
Now everything's updated, the new CI/CD runs. Packages not built yet are shown [here](https://abs-cd.oscloud.info/).

**Comment by saya-rbt** [comment]
Hi, I am running through the same issue. I've been trying to add the `oscloud` repository as well, and the old keys still gets picked up automatically. I tried adding the new one with the correct keyserver like this:
```
$ sudo pacman-key --recv-keys CB222E7EBC11D682AAC8B317A4A0D73114FDE6FC --keyserver keyserver.ubuntu.com
gpg: key A4A0D73114FDE6FC: public key "Oskar Roesler (Username: bionade24) <o.roesler@oscloud.info>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Unfortunately, trying to upgrade my package list now returns this problem:
```
$ sudo pacman -Syu
error: oscloud: signature from "Oskar Roesler (Username: bionade24) <o.roesler@oscloud.info>" is unknown trust
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 [...]
 oscloud               294.4 KiB  1672 KiB/s 00:00 [----------------------] 100%
 oscloud.sig           566.0   B  18.4 KiB/s 00:00 [----------------------] 100%
error: oscloud: signature from "Oskar Roesler (Username: bionade24) <o.roesler@oscloud.info>" is unknown trust
error: failed to update oscloud (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

Trying to refresh the keys gives me this:
```
$ sudo pacman-key --refresh-keys
gpg: refreshing 136 keys from hkps://hkps.pool.sks-keyservers.net:443
gpg: keyserver refresh failed: General error
==> ERROR: A specified local key could not be updated from a keyserver.
```

Is there something I am missing?

**Comment by bionade24** [comment]
> Is there something I am missing?
Yes, you have to trust the key.
Either run `pacman-key --lsign-key <id>` or `pacman-key --edit-key <ID>` and then `trust` in the menu.

Btw: if you experience any issues, with the packages, they currently get rebuild, wait a bit.

**Comment by saya-rbt** [comment]
Awesome, signing the key locally made it work for me. Thanks a lot!
